### ISSUE TITLE
Doesn't work with fish shell

### ISSUE THREAD

**Issue by asgeo1** [reisub0/hot-reload.vim#2]
I just changed the command to `silent execute '!kill -SIGUSR1 (pgrep -f flutter_tool)'` and now it works for me.  Just posting this here in case it helps anyone else.

**Comment by autolyticus** [comment]
@asgeo1 Thanks for bringing this to my notice!

Please verify that the new update solves this issue.

Cheers!

**Comment by asgeo1** [comment]
Thanks, it worked well :-)
