### ISSUE TITLE
Doesn't work under tmux

### ISSUE THREAD

**Issue by rodrigore** [reisub0/hot-reload.vim#3]
If I save the file in zsh session it work but if I run zsh under a tmux session, vim show the next message:

> zsh:1: no matches found: [f]lutter_tool.*run

**Comment by autolyticus** [comment]
Hey @rodrigore and thanks for bringing this to my notice. 

I was unable to reproduce this issue with an empty zshrc and tmux.conf. 

Could you give me more details about your configuration?

**Comment by rodrigore** [comment]
Hey @reisub0 Im using Mac OS with:

- iTerm2 Build 3.2.20180201-nightly
- Tmux 2.7
- VIM 8.1.202
- My dotfiles are https://github.com/rodrigore/dotfiles

I run:

- flutter create demo
- open -a Simulator
- Open vim in another split of tmux
- Change something to demo/lib/main.dart
- Save
- Get zsh:1: no matches found: [f]lutter_tool.*run

![image](https://user-images.githubusercontent.com/1557305/53295163-49aa4200-37d4-11e9-8049-a194bb3c35b3.png)

**Comment by autolyticus** [comment]
@rodrigore I should admit that I don't really have any idea why the behaviour is different under tmux. 

I do have a hunch, and I've pushed a fix to master. 
I think the square brackets in the pattern are being interpreted as meaningful characters in Zsh. I've added quotes and that should hopefully fix the issue. But it still doesn't quite explain why it only gives this issue within tmux.

Could you please update the plugin and check whether it still gives you the same issue?

**Comment by rodrigore** [comment]
@[reisub0 nice! now it works under tmux.  Thank you 👍
